const $=id=>document.getElementById(id);
let words=[],i=0,timer=null,running=false,started=0,elapsed=0,sessions=Number(localStorage.getItem("rsvpSessions")||0),best=Number(localStorage.getItem("rsvpBest")||0),mode="practice";
const samples={uk:"Швидке читання — це навичка, яку можна розвивати регулярною практикою. RSVP показує слова послідовно в одному місці, допомагаючи зменшити зайві рухи очей і тримати стабільний темп. Починай із комфортної швидкості, а потім поступово її збільшуй.",en:"Speed reading is a skill you can build with regular practice. RSVP presents words in one focused location, helping reduce unnecessary eye movement and maintain a steady pace. Start comfortably, then increase your speed gradually.",de:"Schnelles Lesen ist eine Fähigkeit, die du durch regelmäßiges Training entwickeln kannst. RSVP zeigt Wörter an einer festen Stelle und hilft dabei, unnötige Augenbewegungen zu reduzieren. Beginne in einem angenehmen Tempo und steigere dich langsam."};
const T={uk:{brand:"Швидке читання",ey:"FOCUS • READ • IMPROVE",title:"Тренуй швидкість. <span>Зберігай розуміння.</span>",sub:"RSVP показує слова в одному фокусі, щоб ти міг читати швидше без зайвих рухів очей.",sessions:"сесій",ready:"Готово",reading:"Читаємо",paused:"Пауза",done:"Завершено",start:"Старт",pause:"Пауза",reset:"Скинути",speed:"Швидкість",modes:"Режим тренування",practice:"Тренування",practiceSub:"Працюй у своєму темпі",test:"Тест швидкості",testSub:"60 секунд • твій WPM",marathon:"Марафон",marathonSub:"Без таймера • максимум фокусу",custom:"Мій текст",customSub:"Працюй із власним текстом",level:"Рівень",words:"СЛІВ",time:"ЧАС",current:"ПОТОЧНИЙ WPM",best:"РЕКОРД WPM",text:"Текст для тренування",sample:"Приклад",clear:"Очистити",settings:"Налаштування",punct:"Пауза на розділових",punctSub:"Довше після . , ! ?",long:"Довгі слова",longSub:"+25% часу для 10+ символів",size:"Розмір слова",footer:"Твій темп. Твій прогрес. Твій фокус."},
en:{brand:"Speed Reading",ey:"FOCUS • READ • IMPROVE",title:"Train your speed. <span>Keep comprehension.</span>",sub:"RSVP keeps words in one focus point so you can read faster with less eye movement.",sessions:"sessions",ready:"Ready",reading:"Reading",paused:"Paused",done:"Completed",start:"Start",pause:"Pause",reset:"Reset",speed:"Speed",modes:"Training mode",practice:"Practice",practiceSub:"Work at your own pace",test:"Speed test",testSub:"60 seconds • your WPM",marathon:"Marathon",marathonSub:"No timer • maximum focus",custom:"My text",customSub:"Use your own material",level:"Level",words:"WORDS",time:"TIME",current:"CURRENT WPM",best:"BEST WPM",text:"Training text",sample:"Sample",clear:"Clear",settings:"Settings",punct:"Punctuation pause",punctSub:"Longer after . , ! ?",long:"Long words",longSub:"+25% time for 10+ chars",size:"Word size",footer:"Your pace. Your progress. Your focus."},
de:{brand:"Schnelllesen",ey:"FOCUS • READ • IMPROVE",title:"Trainiere dein Tempo. <span>Behalte das Verständnis.</span>",sub:"RSVP hält Wörter in einem Fokuspunkt, damit du schneller und mit weniger Augenbewegungen liest.",sessions:"Sitzungen",ready:"Bereit",reading:"Lesen",paused:"Pause",done:"Fertig",start:"Start",pause:"Pause",reset:"Zurücksetzen",speed:"Tempo",modes:"Trainingsmodus",practice:"Training",practiceSub:"In deinem eigenen Tempo",test:"Geschwindigkeitstest",testSub:"60 Sekunden • dein WPM",marathon:"Marathon",marathonSub:"Ohne Timer • maximaler Fokus",custom:"Mein Text",customSub:"Eigenes Material verwenden",level:"Stufe",words:"WÖRTER",time:"ZEIT",current:"AKTUELLES WPM",best:"BESTES WPM",text:"Trainingstext",sample:"Beispiel",clear:"Leeren",settings:"Einstellungen",punct:"Pausen bei Satzzeichen",punctSub:"Länger nach . , ! ?",long:"Lange Wörter",longSub:"+25% Zeit für 10+ Zeichen",size:"Wortgröße",footer:"Dein Tempo. Dein Fortschritt. Dein Fokus."}};
function tokenize(){words=$("text").value.trim().split(/\s+/).filter(Boolean);i=0;$("textCount").textContent=words.length+" words";show();$("progress").textContent="0 / "+words.length}
function show(){if(!words.length){$("word").textContent="—";$("progress").textContent="0 / 0";return}$("word").textContent=words[Math.min(i,words.length-1)];$("progress").textContent=Math.min(i+1,words.length)+" / "+words.length;$("wordsStat").textContent=i}
function delay(){let d=60000/+$("speed").value,w=words[i]||"";if($("long").checked&&w.length>9)d*=1.25;if($("punct").checked&&/[.!?,;:]$/.test(w))d*=1.35;return d}
function step(){if(!running)return;if(i>=words.length){finish();return}show();i++;timer=setTimeout(step,delay())}
function start(){if(running)return;if(i>=words.length){i=0;elapsed=0}running=true;started=Date.now()-elapsed;$("status").textContent=T[currentLang].reading;$("play").disabled=true;$("pause").disabled=false;step();clock()}
function pause(){if(!running)return;running=false;clearTimeout(timer);elapsed=Date.now()-started;$("status").textContent=T[currentLang].paused;$("play").disabled=false;$("pause").disabled=true}
function finish(){running=false;clearTimeout(timer);elapsed=Date.now()-started;sessions++;localStorage.setItem("rsvpSessions",sessions);$("streakNum").textContent=sessions;$("status").textContent=T[currentLang].done;$("play").disabled=false;$("pause").disabled=true;let mins=elapsed/60000;let wpm=Math.round(i/Math.max(mins,.01));if(wpm>best){best=wpm;localStorage.setItem("rsvpBest",best)}$("bestStat").textContent=best}
function reset(){running=false;clearTimeout(timer);i=0;elapsed=0;$("status").textContent=T[currentLang].ready;$("play").disabled=false;$("pause").disabled=true;show();updateClock()}
function clock(){if(running){updateClock();requestAnimationFrame(clock)}}function updateClock(){let s=Math.floor((running?Date.now()-started:elapsed)/1000);$("timeStat").textContent=Math.floor(s/60)+":"+String(s%60).padStart(2,"0")}
function applyLang(){let t=T[currentLang];$("brandSub").textContent=t.brand;$("eyebrow").textContent=t.ey;$("title").innerHTML=t.title;$("subtitle").textContent=t.sub;$("streakLabel").textContent=t.sessions;$("playText").textContent=t.start;$("pauseText").textContent=t.pause;$("resetText").textContent=t.reset;$("speedLabel").textContent=t.speed;$("modesTitle").textContent=t.modes;$("modePractice").textContent=t.practice;$("modePracticeSub").textContent=t.practiceSub;$("modeTest").textContent=t.test;$("modeTestSub").textContent=t.testSub;$("modeMarathon").textContent=t.marathon;$("modeMarathonSub").textContent=t.marathonSub;$("modeCustom").textContent=t.custom;$("modeCustomSub").textContent=t.customSub;$("levelTitle").textContent=t.level;$("statWords").textContent=t.words;$("statTime").textContent=t.time;$("statSpeed").textContent=t.current;$("statBest").textContent=t.best;$("textTitle").textContent=t.text;$("sampleText").textContent=t.sample;$("clear").textContent=t.clear;$("settingsTitle").textContent=t.settings;$("punctTitle").textContent=t.punct;$("punctSub").textContent=t.punctSub;$("longTitle").textContent=t.long;$("longSub").textContent=t.longSub;$("sizeTitle").textContent=t.size;$("footerText").textContent=t.footer;$("status").textContent=running?t.reading:t.ready}
let currentLang=localStorage.getItem("rsvpLang")||"uk";$("lang").value=currentLang;
$("lang").onchange=e=>{currentLang=e.target.value;localStorage.setItem("rsvpLang",currentLang);$("text").value=samples[currentLang];tokenize();applyLang()};
$("sample").onclick=()=>{$("text").value=samples[currentLang];tokenize()};$("clear").onclick=()=>{$("text").value="";tokenize()};$("text").oninput=tokenize;
$("speed").oninput=e=>{$("wpm").textContent=e.target.value;$("speedStat").textContent=e.target.value;document.querySelectorAll(".speed-presets button").forEach(b=>b.classList.toggle("active",b.dataset.wpm===e.target.value));if(running){clearTimeout(timer);timer=setTimeout(step,delay())}};
document.querySelectorAll(".speed-presets button").forEach(b=>b.onclick=()=>{$("speed").value=b.dataset.wpm;$("speed").dispatchEvent(new Event("input"))});
$("size").oninput=e=>{$("word").style.fontSize=e.target.value+"px";$("sizeValue").textContent=e.target.value};
$("play").onclick=start;$("pause").onclick=pause;$("reset").onclick=reset;
document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>{document.querySelectorAll(".mode").forEach(x=>x.classList.remove("active"));b.classList.add("active");mode=b.dataset.mode;if(mode==="test"){$("speed").value=300;$("speed").dispatchEvent(new Event("input"))}});
document.querySelectorAll(".level-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".level-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("levelValue").textContent=b.dataset.level[0].toUpperCase()+b.dataset.level.slice(1)});
$("themeBtn").onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("rsvpLight",document.body.classList.contains("light"))};
document.addEventListener("keydown",e=>{if(e.target.tagName==="TEXTAREA"||e.target.tagName==="INPUT"||e.target.tagName==="SELECT")return;if(e.code==="Space"){e.preventDefault();running?pause():start()}if(e.key.toLowerCase()==="r")reset()});
if(localStorage.getItem("rsvpLight")==="true")document.body.classList.add("light");$("streakNum").textContent=sessions;$("bestStat").textContent=best;$("text").value=samples[currentLang];applyLang();tokenize();